<a href="https://colab.research.google.com/github/TVMSairam123/Day1_DS/blob/main/Day1_DS_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Implementing Numpy using python programming**

In [3]:
#importing libraries

import numpy as np

a = [1,2,3,4] #list

arr1 = np.array(a)
print(arr1)

b = [[1,2,3,4], [4,5,6,7]] #List 2

arr2 = np.array(b)
print(arr2)

[1 2 3 4]
[[1 2 3 4]
 [4 5 6 7]]


In [7]:
import numpy as np
import sys

s = np.range(10000)

print("Size of each element of numpy array in bytes", s.itemsize)
print("size of whole array in byes:", s.size * s.itemsize)


AttributeError: ignored

In [9]:
import numpy as np
import time

a = range(10000)
b = range(10000)

start = time.time() #mark the start time

#list comprehension (multiply each element of a and b)

ab = [(a * b) for a,b in zip(a,b)]

end = time.time() #mark the end time

print("Total time taken:", end - start)

Total time taken: 0.0034189224243164062


In [12]:
import numpy as np

arr3 = np.array([[1,2,3], [4,5,6]], ndmin= 2) #2D np array

print(arr3)

[[1 2 3]
 [4 5 6]]


In [14]:
arr4 = np.array([[1,2,3],[4,5,6]])

print(arr4.dtype)
print(arr4.ndim)
print(arr4.shape)
print(arr4.size)

int64
2
(2, 3)
6


In [17]:
zero1 = np.zeros((2,2))

print(zero1)

[[0. 0.]
 [0. 0.]]


In [22]:
import numpy as np
c = np.arange(3,10,2)

print(type(c))

<class 'numpy.ndarray'>


In [23]:
a = [1,2,3,4,5]

b = np.array(a)

print(b)

[1 2 3 4 5]


In [26]:
#slicing - Creating substrings from the main string, if we want to divide the elements in list we can perform slicing .

#indexing- getting the value from a specific index position. or from lower range to upper range
#range(lower, upper+1) - 0 to 10 (0,11)

b[1]
b[4]

5

In [28]:
#Negative Indexing

b[-2]


4

In [31]:
#i want to print variables from 0th index to 2nd index

b[0:3]

array([1, 2, 3])

In [33]:
#Updating values using numpy
b[0] = 10


In [34]:
print(b)

[10  2  3  4  5]


In [35]:
#I want to print elements from 2nd index to remaining

print(b[2: ])

[3 4 5]


In [36]:
print(b[ :3])

[10  2  3]


In [37]:
c = np.array([[1,2,3,4,5], [6,7,8,9,10]])
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
print(c[1])

[ 6  7  8  9 10]


In [42]:
print(c[1][3])

9


# **Pandas Library Implementation**

In [46]:
#pandas is used for handling data and datasets

import pandas as pd

dataset = pd.read_csv("/content/Social_Network_Ads.csv")

In [48]:
dataset.head(15) #by default head() method will return first 5 or random 5 rows in the dataset

Age  EstimatedSalary  Purchased
0    19            19000          0
1    35            20000          0
2    26            43000          0
3    27            57000          0
4    19            76000          0
5    27            58000          0
6    27            84000          0
7    32           150000          1
8    25            33000          0
9    35            65000          0
10   26            80000          0
11   26            52000          0
12   20            86000          0
13   32            18000          0
14   18            82000          0

In [50]:
dataset.tail(20)

Age  EstimatedSalary  Purchased
380   42            64000          0
381   48            33000          1
382   44           139000          1
383   49            28000          1
384   57            33000          1
385   56            60000          1
386   49            39000          1
387   39            71000          0
388   47            34000          1
389   48            35000          1
390   48            33000          1
391   47            23000          1
392   45            45000          1
393   60            42000          1
394   39            59000          0
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

In [51]:
dataset.shape

(400, 3)

In [52]:
#Check information of dataset

dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Age              400 non-null    int64
 1   EstimatedSalary  400 non-null    int64
 2   Purchased        400 non-null    int64
dtypes: int64(3)
memory usage: 9.5 KB


In [54]:
#Description of dataset

dataset.describe()

Age  EstimatedSalary   Purchased
count  400.000000       400.000000  400.000000
mean    37.655000     69742.500000    0.357500
std     10.482877     34096.960282    0.479864
min     18.000000     15000.000000    0.000000
25%     29.750000     43000.000000    0.000000
50%     37.000000     70000.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [63]:
dataset1 = pd.read_html("https://en.wikipedia.org/wiki/Data_science")[0] 
dataset1.head()

0
0                                Part of a series on
1                    Machine learningand data mining
2  Problems Classification Clustering Regression ...
3  Supervised learning.mw-parser-output .nobold{f...
4  Clustering BIRCH CURE Hierarchical k-means Exp...

In [58]:
dataset.Age

0      19
1      35
2      26
3      27
4      19
       ..
395    46
396    51
397    50
398    36
399    49
Name: Age, Length: 400, dtype: int64

In [59]:
dataset.EstimatedSalary

0      19000
1      20000
2      43000
3      57000
4      76000
       ...  
395    41000
396    23000
397    20000
398    33000
399    36000
Name: EstimatedSalary, Length: 400, dtype: int64

In [60]:
dataset[['Age', 'EstimatedSalary', 'Purchased']]

Age  EstimatedSalary  Purchased
0     19            19000          0
1     35            20000          0
2     26            43000          0
3     27            57000          0
4     19            76000          0
..   ...              ...        ...
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

[400 rows x 3 columns]